### ISSUE TITLE
Integrate new resource editor into this app

### ISSUE THREAD

**Issue by rufuspollock** [datopian/ckanext-blob-storage#25]
Integrate new resource editor created here https://github.com/datopian/datapub/issues/1

## Acceptance criteria

* [ ] When this extension is installed, create a new resource UI uses the DataPub app
* [ ] I can quickly pull latest changes from DataPub project into this extension, eg, by running couple of commands

## Tasks

* [x] git submodule vs other approaches
* [ ] remove current implementation of new resource
* [ ] enable the DataPub app
* [x] document

### Git submodule

1. Create submodule in the root directory.
2. Build bundles by `cd ./datapub && yarn && yarn build`
3. Move bundles to fanstatic directory `mv ./static/js/ ./ckanext/external-storage/fanstatic/js/datapub`
4. Keep hashes in the bundle names for version control. Every time a new bundle is built, we will need to update the template.

Do we need to use stylesheets? If yes, we can also move CSS files:

`mv ./static/css/ ./ckanext/external-storage/fanstatic/css/datapub`

### Use pre built bundles

If we build and commit bundles in the DataPub repo, we can use them directly from Github (?):

1. Bundle file is built at `github.com/datopian/datapub/bundle.js` - can't have hashes in file names here as it would break once changed.
2. From CKAN template we import the module...

**Comment by anuveyatsu** [comment]
I've started a PR here #26 

cc @rufuspollock
